package it.eably.backend.model;

import jakarta.persistence.*;
import java.time.LocalDateTime;

/**
 * Entity representing an outbound email queued for asynchronous delivery.
 *
 * <p>Emails are persisted in the {@code email_queue} table and processed by a scheduled
 * retry mechanism. Each entry tracks delivery status, retry count, and error details
 * to support reliable at-least-once delivery semantics.</p>
 *
 * <p>Unlike other model classes, {@code EmailQueue} does <em>not</em> extend
 * {@link BaseEntity} — it manages its own {@code id} and {@code created_at} fields
 * to keep the schema minimal and independent of JPA auditing.</p>
 *
 * @author Alessandro D'Angelo
 * @version 1.0
 */
@Entity
@Table(name = "email_queue")
public class EmailQueue {

    /** Primary key, auto-generated by the database. */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /** Email address of the intended recipient. */
    @Column(name = "recipient_email", nullable = false)
    private String recipientEmail;

    /** Subject line of the email. */
    @Column(name = "subject", nullable = false)
    private String subject;

    /** Full HTML body of the email. */
    @Column(name = "html_content", nullable = false, columnDefinition = "TEXT")
    private String htmlContent;

    /** Optional path to the logo image embedded in the email template. */
    @Column(name = "logo_path")
    private String logoPath;

    /** Current delivery status of this email entry. Defaults to {@link EmailQueueStatus#PENDING}. */
    @Enumerated(EnumType.STRING)
    @Column(name = "status", nullable = false)
    private EmailQueueStatus status = EmailQueueStatus.PENDING;

    /** Number of delivery attempts made so far. */
    @Column(name = "retry_count", nullable = false)
    private int retryCount = 0;

    /** Maximum number of delivery attempts allowed before marking the entry as failed. */
    @Column(name = "max_retries", nullable = false)
    private int maxRetries = 5;

    /** Timestamp when this entry was created. */
    @Column(name = "created_at", nullable = false)
    private LocalDateTime createdAt = LocalDateTime.now();

    /** Timestamp of the most recent delivery attempt, or {@code null} if not yet attempted. */
    @Column(name = "last_attempt_at")
    private LocalDateTime lastAttemptAt;

    /** Error message from the last failed delivery attempt, or {@code null} if none. */
    @Column(name = "error_message", columnDefinition = "TEXT")
    private String errorMessage;

    /** Default no-arg constructor required by JPA. */
    public EmailQueue() {}

    /**
     * Convenience constructor for creating a new email queue entry.
     *
     * @param recipientEmail  the recipient's email address
     * @param subject         the email subject line
     * @param htmlContent     the full HTML body
     * @param logoPath        optional path to the logo image
     */
    public EmailQueue(String recipientEmail, String subject, String htmlContent, String logoPath) {
        this.recipientEmail = recipientEmail;
        this.subject = subject;
        this.htmlContent = htmlContent;
        this.logoPath = logoPath;
    }

    public Long getId() { return id; }
    public String getRecipientEmail() { return recipientEmail; }
    public String getSubject() { return subject; }
    public String getHtmlContent() { return htmlContent; }
    public String getLogoPath() { return logoPath; }
    public EmailQueueStatus getStatus() { return status; }
    public void setStatus(EmailQueueStatus status) { this.status = status; }
    public int getRetryCount() { return retryCount; }
    public void setRetryCount(int retryCount) { this.retryCount = retryCount; }
    public int getMaxRetries() { return maxRetries; }
    public LocalDateTime getCreatedAt() { return createdAt; }
    public LocalDateTime getLastAttemptAt() { return lastAttemptAt; }
    public void setLastAttemptAt(LocalDateTime lastAttemptAt) { this.lastAttemptAt = lastAttemptAt; }
    public String getErrorMessage() { return errorMessage; }
    public void setErrorMessage(String errorMessage) { this.errorMessage = errorMessage; }
}
