# Stripe Configuration (TEST MODE)
stripe.secret-key=${STRIPE_SECRET_KEY:sk_test_REPLACE_ME}
stripe.publishable-key=${STRIPE_PUBLISHABLE_KEY:pk_test_51SnaSUBdYGKVaDjHYwSWyO7AVHDWcu6uziRZaMzq4WIt0fn59i3LKj5pGnYVn5FUkjVPV6H6Nj7Awd02RpEZxZRj00UIc4Pbu1}
