# -------------------------------------------------------
# Profilo macOS 
# -------------------------------------------------------
spring.datasource.url=jdbc:postgresql://localhost:5432/eably_spring
spring.datasource.username=alessandro_dangelo
spring.datasource.password=${DB_PASSWORD:postgres}
